---
title: "QTW_CASE_STUDY_1"
author: "Pankaj Kumar"
date: "5/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r , code = readLines("case_study_functions.R")}
```

## Including Plots

You can also embed plots, for example:

```{r , echo=FALSE}
offline_file_path = "/Users/pankaj/dev/git/smu/qtw/class1/data/offline.final.trace.txt"
  online_file_path = "/Users/pankaj/dev/git/smu/qtw/class1/data/online.final.trace.txt"
```


```{r , echo=FALSE}
offline = readData(offline_file_path )
```


```{r}
offline = offline[ , !(names(offline) %in% c("scanMac", "posZ"))]

length(unique(offline$orientation))

plot(ecdf(offline$orientation))

 

 
with(offline, boxplot(orientation ~ angle,
                      xlab = "nearest 45 degree angle",
                      ylab="orientation"))

 
 



```

```{r}
locDF = with(offline,
             by(offline, list(posX, posY), function(x) x))
 
locDF = locDF[ !sapply(locDF, is.null) ]
locCounts = sapply(locDF, nrow)
locCounts = sapply(locDF,
                   function(df)
                     c(df[1, c("posX", "posY")], count = nrow(df)))
class(locCounts)
 dim(locCounts)
 locCounts[ , 1:8]
 locCounts = t(locCounts)
 plot(locCounts, type = "n", xlab = "", ylab = "")
 text(locCounts, labels = locCounts[,3], cex = .8, srt = 45)


```



 

```{r}
bwplot(signal ~ factor(angle) | mac, data = offline,
        subset = posX == 2 & posY == 12
        & mac != "00:0f:a3:39:dd:cd",
        layout = c(2,3))
 
 summary(offline$signal)
```


```{r}
densityplot( ~ signal | mac + factor(angle), data = offline,
              subset = posX == 24 & posY == 4 &
                mac != "00:0f:a3:39:dd:cd",
              bw = 0.5, plot.points = FALSE)
```


```{r}
offline$posXY = paste(offline$posX, offline$posY, sep = "-")
 
 
 byLocAngleAP = with(offline,
                     by(offline, list(posXY, angle, mac),
                        function(x) x))
 # Then we can calculate summary statistics on each of these data frames with
 signalSummary =
   lapply(byLocAngleAP,
          function(oneLoc) {
            ans = oneLoc[1, ]
            ans$medSignal = median(oneLoc$signal)
            ans$avgSignal = mean(oneLoc$signal)
            ans$num = length(oneLoc$signal)
            ans$sdSignal = sd(oneLoc$signal)
            ans$iqrSignal = IQR(oneLoc$signal)
            ans
          })
```


```{r}

offlineSummary = do.call("rbind", signalSummary)

 
 breaks = seq(-90, -30, by = 5)
 bwplot(sdSignal ~ cut(avgSignal, breaks = breaks),
        data = offlineSummary,
        subset = mac != "00:0f:a3:39:dd:cd",
        xlab = "Mean Signal", ylab = "SD Signal")

 

```


```{r}
subMacs = names(sort(table(offline$mac), decreasing = TRUE))[1:7]

 oneAPAngle = subset(offline, mac == subMacs[5] & angle == 0)
 
 oneAPAngle = subset(offlineSummary,
                     mac == subMacs[5] & angle == 0)
 
 
 smoothSS = Tps(oneAPAngle[, c("posX","posY")],
                oneAPAngle$avgSignal)

 
 vizSmooth = predictSurface(smoothSS)
 
 plot.surface(vizSmooth, type = "C")
 
 
 points(oneAPAngle$posX, oneAPAngle$posY, pch=19, cex = 0.5)
 
 

 
 
```


```{r}

surfaceSS(data = offlineSummary, mac == subMacs[5] & angle == 0)
 
 
 parCur = par(mfrow = c(2,2), mar = rep(1, 4))
 
    mapply(surfaceSS, mac = subMacs[ rep(c(5, 1), each = 2) ],
          angle = rep(c(0, 135), 2),
          data = list(data = offlineSummary))
    
  par(parCur)
  
 

```


```{r}
subMacs = names(sort(table(offline$mac), decreasing = TRUE))[1:7]

 offlineSummary = subset(offlineSummary, mac != subMacs[2])
 
  AP = matrix( c( 7.5, 6.3, 2.5, -.8, 12.8, -2.8,
                  1, 14, 33.5, 9.3, 33.5, 2.8),
               ncol = 2, byrow = TRUE,
               dimnames = list(subMacs[ -2 ], c("x", "y") ))

  AP
  
  diffs = offlineSummary[ , c("posX", "posY")] -
    AP[ offlineSummary$mac, ]

  
  offlineSummary$dist = sqrt(diffs[ , 1]^2 + diffs[ , 2]^2)
  xyplot(signal ~ dist | factor(mac) + factor(angle),
         data = offlineSummary, pch = 19, cex = 0.3,
         xlab ="distance")

```


```{r}
  macs = unique(offlineSummary$mac)

  online = readData(online_file_path, subMacs = macs)
  
  online$posXY = paste(online$posX, online$posY, sep = "-")
  #We use this new variable to determine that we have 60 unique test locations, i.e.,
  length(unique(online$posXY))
  #Also, we tally the number of signal strengths recorded at each location with
  tabonlineXYA = table(online$posXY, online$angle)
  tabonlineXYA[1:6, ]
  
  keepVars = c("posXY", "posX","posY", "orientation", "angle")
  byLoc = with(online,
               by(online, list(posXY),
                  function(x) {
                    ans = x[1, keepVars]
                    avgSS = tapply(x$signal, x$mac, mean)
                    y = matrix(avgSS, nrow = 1, ncol = 6,
                               dimnames = list(ans$posXY, names(avgSS)))
                    cbind(ans, y)
                  }))
  onlineSummary = do.call("rbind", byLoc)
  
  dim(onlineSummary)
  
  
  names(onlineSummary)
  
  
  refs = seq(0, by = 45, length = 8)
  
  train130 = selectTrain(130, offlineSummary, m = 3)
  head(train130)
  
  length(train130[[1]])
  
  estXYk3 = predXY(newSignals = onlineSummary[ , 6:11],
                   newAngles = onlineSummary[ , 4],
                   offlineSummary, numAngles = 3, k = 3)
  
  estXYk1 = predXY(newSignals = onlineSummary[ , 6:11],
                   newAngles = onlineSummary[ , 4],
                   offlineSummary, numAngles = 3, k = 1)
  
                   
  calcError =
    function(estXY, actualXY)
      sum( rowSums( (estXY - actualXY)^2) )
  
  actualXY = onlineSummary[ , c("posX", "posY")]
  sapply(list(estXYk1, estXYk3), calcError, actualXY)
  
  
 
  
 

```


```{r}


 v = 11
  permuteLocs = sample(unique(offlineSummary$posXY))
  permuteLocs = matrix(permuteLocs, ncol = v,
                       nrow = floor(length(permuteLocs)/v))
  
  onlineFold = subset(offlineSummary, posXY %in% permuteLocs[ , 1])
  
  
  keepVars = c("posXY", "posX","posY", "orientation", "angle")
  onlineCVSummary = reshapeSS(offlineSummary, keepVars = keepVars,
                              sampleAngle = TRUE)
  
  
  offlineFold = subset(offlineSummary,
                       posXY %in% permuteLocs[ , -1])
  
  estFold = predXY(newSignals = onlineFold[ , 6:11],
                   newAngles = onlineFold[ , 4],
                   offlineFold, numAngles = 3, k = 3)
  
  actualFold = onlineFold[ , c("posX", "posY")]
  calcError(estFold, actualFold)
  
  K = 20
  err = rep(0, K)
  for (j in 1:v) {
    onlineFold = subset(onlineCVSummary,
                        posXY %in% permuteLocs[ , j]) 
    offlineFold = subset(offlineSummary,
                         posXY %in% permuteLocs[ , -j])
    actualFold = onlineFold[ , c("posX", "posY")]
    for (k in 1:K) {
      print(paste("running for  j ", j ," k ",  k))
      estFold = predXY(newSignals = onlineFold[ , 6:11],
                       newAngles = onlineFold[ , 4],
                       offlineFold, numAngles = 3, k = k)
      err[k] = err[k] + calcError(estFold, actualFold)
    }
  }
  
  
  estXYk5 = predXY(newSignals = onlineSummary[ , 6:11],
                   newAngles = onlineSummary[ , 4],
                   offlineSummary, numAngles = 3, k = 5)

    calcError(estXYk5, actualXY)

    
    plot(estXYk5)
    plot(err, type = 'l')
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
